name: Gradle Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Save Secrets into local.properties
        env:
          TYPE_SENSE_API_KEY: ${{secrets.TYPE_SENSE_API_KEY}}
          TYPE_SENSE_HOST: ${{secrets.TYPE_SENSE_HOST}}
        run: |
          touch ./local.properties
          echo TYPE_SENSE_API_KEY=$TYPE_SENSE_API_KEY >> ./local.properties
          echo TYPE_SENSE_HOST=$TYPE_SENSE_HOST >> ./local.properties

      - name: Set JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Build
        run: ./gradlew build
